### ISSUE TITLE
Problems running addons with css files

### ISSUE THREAD

**Issue by lstrzebinczyk** [ember-codemods/ember-module-migrator#62]
Hey

I belive that application created or migrated via this migrator and blueprint is unable to recognize sass files in addons. I created an application that reproduces this error, available at: https://github.com/KillaPL/ember-unified-structure-with-modal

Steps to manually reproduce:

```
ember init -b ember-module-unification-blueprint
ember install ember-modal-dialog
ember install ember-cli-sass
yarn
```

add this to `app.css`:

@import "ember-modal-dialog/ember-modal-structure";
@import "ember-modal-dialog/ember-modal-appearance";

and this to `src/ui/index/template.hbs`:

```
{{#modal-dialog}}
  Oh hai there!
{{/modal-dialog}}
```

when this application is started, I receive this error and log:

```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /home/killa/workspace/ember-unified-structure-with-modal/tmp/sass_compiler-input_base_path-AxZJaZnz.tmp
    at Object.findFileSync (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/broccoli-sass-source-maps/index.js:63:31)
    at /home/killa/workspace/ember-unified-structure-with-modal/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/broccoli-merge-trees/index.js:36:53)
    at SASSPlugin.toTree (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli-sass/index.js:40:10)
    at /home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
    at EmberApp.styles (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli/lib/broccoli/ember-app.js:1442:32)
    at EmberApp.toArray (/home/killa/workspace/ember-unified-structure-with-modal/node_modules/ember-cli/lib/broccoli/ember-app.js:1786:12)
```

I'm happy to help solving this, but I will require some directions. Is this an actul issue with the embers libraries? Or did I set this up wrong?

Note: Similiar issue happens with other libraries with sass files, like ember-power-calendar etc.

**Comment by andyhot** [comment]
This seems the same problem as reported in https://github.com/ember-cli/ember-cli/issues/6332#issuecomment-295279717

But it's not really related to ember-module-migrator - more like n issue of the new resolver. @mixonic where should this best be addressed?

**Comment by KillaPL** [comment]
If neede, I'm happy to close this issue and reopen where it's appriopriate : )

**Comment by alan-hadyk** [comment]
I found a solution - https://github.com/KillaPL/ember-unified-structure-with-modal/pull/1/files . It was related to `ember-cli-sass` config in `ember-cli-build.js`.

**Comment by rameramwe** [comment]
@alan-hadyk thank you very much for sharing your solution... the same problem was making my life miserable for almost 3 days!! Thanks a lot and have a lovely new year :D 👍 💯

**Comment by lstrzebinczyk** [comment]
I'm gonna close this one, it's quite obsolete now; )
